### ISSUE TITLE
MemoryError when tessellating with GWR

### ISSUE THREAD

**Issue by francoislaurent** [DecBayComp/TRamWAy#2]
With 2916201 lines in file *trajectories.txt* and very high resolution (average translocation distance: 0.121922200919), tessellating with GWR raises a `MemoryError` exception:
```
python -m tramway tessellate gwr -i trajectories.txt -o VLP_WT_2.rwa -s 20 -d .005 -l gwr_20 --pass-count .1
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/francois/github/TRamWAy/tramway/__main__.py", line 489, in <module>
    main()
  File "/home/francois/github/TRamWAy/tramway/__main__.py", line 479, in main
    args.func(args)
  File "/home/francois/github/TRamWAy/tramway/__main__.py", line 124, in sample
    tessellate(input_file, output_file=output_file, method=method, **kwargs)
  File "/home/francois/github/TRamWAy/tramway/helper/tessellation.py", line 389, in tessellate
    tess.tessellate(data, verbose=verbose, **tessellate_kwargs)
  File "/home/francois/github/TRamWAy/tramway/tessellation/gwr/__init__.py", line 158, in tessellate
    self._postprocess(points, verbose)
  File "/home/francois/github/TRamWAy/tramway/tessellation/gwr/__init__.py", line 190, in _postprocess
    ix = np.argmin(cdist(points, self._cell_centers), axis=1)
  File "/usr/lib/python2.7/dist-packages/scipy/spatial/distance.py", line 2077, in cdist
    dm = np.zeros((mA, mB), dtype=np.double)
MemoryError
```

**Comment by francoislaurent** [comment]
with *kmeans*:
```
python3 -m tramway tessellate kmeans -c 20 -d 0 -n 20 -i VLP/WT/2/trajectories.txt -o vlp_2_all.rwa -l kmeans_20_knn_20
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/francois/github/TRamWAy/tramway/__main__.py", line 484, in <module>
    main()
  File "/home/francois/github/TRamWAy/tramway/__main__.py", line 474, in main
    args.func(args)
  File "tramway/__main__.py", line 99, in sample
    tessellate(input_file, output_file=output_file, method=method, **kwargs)
  File "tramway/helper/tessellation.py", line 444, in tessellate
    cell_index = tess.cell_index(xyt_data, knn=knn, **partition_kwargs)
  File "tramway/tessellation/base.py", line 826, in cell_index
    raise memory_error
UnboundLocalError: local variable 'memory_error' referenced before assignment
```
