### ISSUE TITLE
Ran out of input

### ISSUE THREAD

**Issue by Brieuc-Chauvin** [DecBayComp/TRamWAy#29]
```>>> infer('bowl.rwa', 'stochastic.dv')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Brieuc\AppData\Local\Programs\Python\Python37\lib\site-packages\tramway\helper\inference.py", line 418, in infer1
    jeffreys_prior=jeffreys_prior, rgrad=rgrad, snr_extensions=snr_extensions, **kwargs)
  File "C:\Users\Brieuc\AppData\Local\Programs\Python\Python37\lib\site-packages\tramway\helper\inference.py", line 246, in infer
    x = cells.run(getattr(self.module, self.setup['infer']), **kwargs)
  File "C:\Users\Brieuc\AppData\Local\Programs\Python\Python37\lib\site-packages\tramway\inference\base.py", line 765, in run
    result = function(self, *args, **kwargs)
  File "C:\Users\Brieuc\AppData\Local\Programs\Python\Python37\lib\site-packages\tramway\inference\stochastic_dv.py", line 487, in infer_stochastic_DV
    gradient_subspace, descent_subspace, args, **sbfgs_kwargs)
  File "C:\Users\Brieuc\AppData\Local\Programs\Python\Python37\lib\site-packages\tramway\inference\optimization.py", line 1140, in minimize_sparse_bfgs1
    sched.run()
  File "C:\Users\Brieuc\AppData\Local\Programs\Python\Python37\lib\site-packages\tramway\core\parallel\__init__.py", line 383, in run
    w.start()
  File "C:\Users\Brieuc\AppData\Local\Programs\Python\Python37\lib\multiprocessing\process.py", line 112, in start
    self._popen = self._Popen(self)
  File "C:\Users\Brieuc\AppData\Local\Programs\Python\Python37\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Users\Brieuc\AppData\Local\Programs\Python\Python37\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "C:\Users\Brieuc\AppData\Local\Programs\Python\Python37\lib\multiprocessing\popen_spawn_win32.py", line 89, in __init__
    reduction.dump(process_obj, to_child)
  File "C:\Users\Brieuc\AppData\Local\Programs\Python\Python37\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
AttributeError: Can't pickle local object '_fun_args.<locals>.<lambda>'
>>> Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\Brieuc\AppData\Local\Programs\Python\Python37\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "C:\Users\Brieuc\AppData\Local\Programs\Python\Python37\lib\multiprocessing\spawn.py", line 115, in _main
    self = reduction.pickle.load(from_parent)
EOFError: Ran out of input
```

**Comment by francoislaurent** [comment]
multiprocessing has been disabled for Windows.
Please `python3 -m pip install --upgrade tramway`
