### ISSUE TITLE
Too many open files

### ISSUE THREAD

**Issue by francoislaurent** [DecBayComp/TRamWAy#33]
TODO: investigate the following error during call to `RWAnalyzer.run()` with `SingularitySlurm` environment:
```
Traceback (most recent call last):
  File "/master/home/flaurent/scratch/tmp.07K069ybpD/tmpohae94ld.py", line 12, in <module>
  File "/usr/local/lib/python3.6/dist-packages/tramway/analyzer/env/environments.py", line 612, in _combine_analyses
  File "/usr/lib/python3.6/tempfile.py", line 483, in mkstemp
  File "/usr/lib/python3.6/tempfile.py", line 401, in _mkstemp_inner
OSError: [Errno 24] Too many open files: '/master/home/flaurent/scratch/tmp.07K069ybpD/tmp1k6vvkjl.rwa'
```

**Comment by francoislaurent** [comment]
The above issue is actually hit on one HPC server (GPUlab) and not others (e.g. Maestro).

Upcoming *tramway 0.6.2* will bring various optimizations related to open and temporary files, but these optimizations do not seem to help in this specific case.
